quarkus.mongodb.connection-string=${MONGO_URL}
quarkus.mongodb.database=${MONGO_NAME}
quarkus.http.port=8080

mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.token.cookie=jwt
mp.jwt.token.header=Cookie
mp.jwt.verify.issuer=https://acme.org/issuer
quarkus.http.auth.proactive=false

quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:5173,http://217.182.68.66:8100,https://mama-solution.duckdns.org
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS,HEAD
quarkus.http.cors.headers=origin,content-type,accept,authorization,x-requested-with
quarkus.http.cors.access-control-allow-credentials=true
